### ISSUE TITLE
关于{ ...item, vote: ++item.vote} 报错

### ISSUE THREAD

**Issue by chinadbo** [xuchaobei/react-book#1]
![Uploading 屏幕快照 2018-04-15 18.19.56.png…]()

**Comment by chinadbo** [comment]
<img width="852" alt="2018-04-15 18 19 56" src="https://user-images.githubusercontent.com/4602050/38777422-01b9d498-40da-11e8-967d-966b21635b06.png">

**Comment by xuchaobei** [comment]
@chinadbo 
具体是哪个示例的报的错？从你的报错路径上看，不是直接运行的项目示例。
“...”的解构语法是ES6中的新语法，如果是自己搭建的环境，需要确保你的环境（主要是babel配置）支持这种写法。

**Comment by chinadbo** [comment]
是在我搭建的环境下出现的问题，babel-preset-env可能还不支持spread扩展运算符。用Object.assign解决了问题，谢谢您的回复。
