### ISSUE TITLE
production环境下store报错

### ISSUE THREAD

**Issue by niuzz** [xuchaobei/react-book#2]
production环境下，报找不到store,

`// redux/index.js
finalCreateStore = applyMiddleware(thunk)(createStore);`
是否需要改成
`// redux/index
finalCreateStore = compose(applyMiddleware(thunk))(createStore);
`

**Comment by xuchaobei** [comment]
@niuzz redux/index.js，没有这行代码，你说的是redux/configureStore.js吧 ？

不需要修改，我也验证了bbs-redux这个项目，production环境并没有store到不到的错误。如果你的问题还存在，请指出具体是哪一个示例代码报的错？并贴一下详细的编译信息和报错信息。

另外，需要注意，以production模式运行代码，示例代码中的api代理是不起作用的，需要自己额外配置代理，保证接口访问到正确的云服务上的接口。

**Comment by niuzz** [comment]
that's ok
