### ISSUE TITLE
第三章   react16-error-boundary 的代码运行错误

### ISSUE THREAD

**Issue by ycshill** [xuchaobei/react-book#4]
![image](https://user-images.githubusercontent.com/16410254/42925611-50dc6f32-8b61-11e8-9ce5-ec463ce7296a.png)

点击更新后，如上图所示

**Comment by xuchaobei** [comment]
这节的示例是为了演示Error Boundary的效果，异常是故意制造的，因为点击更新时，将user设置为了null。可以再仔细看下书中的说明。

**Comment by ycshill** [comment]
` {/* <ErrorBoundary> */}
          <Profile user={this.state.user} />
        {/* </ErrorBoundary> */}`
上面的代码被注释，也会出现和上图一样的报错，而且书中说"会在页面上创建一个浮层显示错误信息"，但是没有显示啊，这是其一，另外我觉得捕捉到错误后，不应该在界面上显示“Oops, something went wrong!” 才对

**Comment by xuchaobei** [comment]
书中有写到：要正确观察ErrorBoundary的效果，需要先关闭错误浮层。
因为当前这个错误浮层是react在开发环境下运行时添加上的，你点击浮层上的“X”关闭浮层后，就能看到Error Boundary的效果了。

**Comment by ycshill** [comment]
你可以试一下没有浮层的, 另外举例的代码是我上面说的那个意思吗？

**Comment by xuchaobei** [comment]
1. 当以开发模式（npm start）运行程序时，react会把代码抛出的错误通过一个浮层展现出来，主要是出于开发调试的作用，如果是npm build编译后的代码再部署的话，react是不会显示这个错误浮层的。所以以npm start运行程序时，为了观察到Error Boundary的效果，需要点击浮层上的“X”关闭浮层。

2. “Oops, something went wrong!” 这个错误信息是由ErrorBoundary组件显示出来的，当有错误抛出时，ErrorBoundary的componentDidCatch会被调用，进而在render中渲染出上面的错误信息。你可以再仔细看下ErrorBoundary的代码。
