### ISSUE TITLE
Section 4.3.2 Page 75页 的 currentUser疑问？

### ISSUE THREAD

**Issue by archerli** [xuchaobei/react-book#8]
> const currentUser = filterUsers.length > 0 ? filterUsers[0] : null;

> <UserDetail currentUser = {currentUser} />

这个例子中，是否是应该要初始化
currentUserId  为 0 
然后设置 
const currentUser = filterUsers.length > 0 ? filterUsers[**currentUserId**] : null;

因为在 handleSetCurrentUser 的时候，只是 更新了 currentUserId 的值？

**Comment by xuchaobei** [comment]
> 因为在 handleSetCurrentUser 的时候，只是 更新了 currentUserId 的值？

不理解这句话。

现在currentUserId初始化值为null，没有必要设置为0
